version: '3.8'

services:
  parser:
    build: ./pythonParser
    networks: [micro_net]

  commenter:
    build: commenter
    networks: [micro_net]
    environment:
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}

  inserter:
    build: ./commentInserter
    networks: [micro_net]
    volumes:
    - ./commentInserter:/app

networks:
  micro_net:
    driver: bridge